
http {
    server {
        #listen     80
        listen      8080;
        server_name localhost;
        #error_page 404         /error/404.html;
        error_page 500         /error/50X.html;
        error_page 501         /error/50X.html;
        error_page 502         /error/50X.html;
        error_page 503         /error/50X.html;
        error_page 504         /error/50X.html;
        error_page 505         /error/50X.html;

        client_max_body_size 3000000;
        location / {
            root    www;
            index   index.html index.htm;
            limit_except GET;
        }
        location /tapir {
            root    www;
            index   index.html;
        }
        location /hack {
            root    www;
            index   tester.html;
            limit_except GET;
        }
        location /mail_send {
            root www;
            autoindex on;
            index _;
        }
        location /cgi-bin {
            root www;
            is_cgi_py true;
        }
        location /notwork {
            root www;
            index   apocalypse.html;
            limit_except GET;
        }
        location /tapir/assets/img {
            root www;
            limit_except POST;
        }
        location /upload {
            root www;
            limit_except GET;
        }
    }
}
