
http {
    server {
        #listen     80
        listen      8080;
        server_name localhost;
        error_page 404 /terst.html;
        location / {
            root    www;
            index   index.html index.htm;
        }
        location /tapir {
            root    www;
            index   index.html;
        }
        location /test {
            root    www;
            is_cgi_py false;
        }
    }
}
