
http {
    server {
        #listen     80
        listen      8080;
        server_name localhost;
        location / {
            root    /www;
            index   index.html index.htm;
        }
        location /tapir {
            root    /www;
            index   index.html;
        }
    }
}
