events {
    worker_connections   512;
}

http {
    client_header_buffer_size   8k;
    client_max_body_size        1m;
    server {
        listen      8080;
        server_name localhost;
        default_type epoll;
        location / {
            root    www;
            index   index.html index.htm;
        }
        location /test/ {
            root    www;
            index   index.html;
        }
    }
}
